// Manually written English paragraphs for the "time" and "zen" modes when
// practicing English, the counterpart of paragraphs.js. They're also cut at
// their periods into the sentences dictation reads out and the course's last
// lesson types, so most sentences stay between six and sixteen words.
export const englishParagraphs = [
  "Technology has changed the way we talk to each other and the way we work. A letter that once took weeks to arrive now reaches its reader in seconds. Most people carry a small computer in their pocket all day long. It keeps their maps, their music, their photos and their calendar in one place. Engineers keep finding new ways to make these devices faster and lighter. Still, the best tool is only as useful as the person holding it. Learning to use it well takes patience, curiosity and a little practice every day.",
  "Learning a new language is like opening a door to another world. At first every sentence feels slow and clumsy in your mouth. You forget simple words and mix up the order of the ones you know. Then one day you understand a joke without translating it in your head. That small moment makes all the hard work feel worth it. Reading, listening and speaking a little every day works better than cramming once a week. Mistakes are not a sign of failure; they are how the brain learns.",
  "The forest was quiet except for the sound of the wind in the tall pines. A narrow path wound between the trees and down toward the river. Sunlight fell through the branches in thin golden lines. Somewhere above, a woodpecker tapped a steady rhythm on a dead trunk. The air smelled of wet earth, moss and fallen leaves. A deer lifted its head, watched us for a moment, and slipped away. We walked on without speaking, as if the forest had asked us to keep its secret.",
  "Music is a language that almost everyone understands. A simple melody can make a crowded room fall silent in a few seconds. Some songs remind us of a summer, a friend or a long drive at night. Musicians spend years learning scales before they can play freely. Jazz players often say that the notes you leave out matter as much as the ones you play. Today anyone with a laptop can record a song at home. What has not changed is the joy of making a sound that moves someone else.",
  "Cooking at home does not have to be complicated or expensive. A few fresh ingredients and a good knife can go a long way. Start with a pot of water, some pasta, garlic and olive oil. Let the garlic turn golden, but never let it burn. Add a handful of chopped herbs and a squeeze of lemon at the end. Taste as you go and adjust the salt little by little. The best meals are often the simplest ones, shared with people you like.",
  "Traveling by train is one of the most relaxing ways to see a country. You can read, sleep or simply watch the fields go by the window. Small villages appear and disappear between the hills. At each station people step on and off with bags, bikes and flowers. Nobody is in a hurry to fasten a seat belt or turn off a phone. You arrive in the middle of the city instead of an airport far away. The journey itself becomes part of the trip.",
  "Every sport teaches something that goes beyond the game itself. A runner learns that the last mile is mostly won in the mind. A basketball team learns to trust a pass before the player has turned around. Swimmers learn to breathe calmly while every muscle wants to stop. Losing a close match can teach more than an easy victory. Coaches often say that talent opens the door, but practice keeps it open. The habits built on the field tend to follow us everywhere else.",
  "Big cities never really sleep; they only change their rhythm. In the early morning, bakers light their ovens and buses start their first routes. By nine the streets are full of people walking quickly with coffee in hand. Lunch brings a short pause, with crowded tables in every small square. In the evening the lights come on in thousands of windows at once. Taxis, music and laughter fill the avenues until late at night. Then, for a few quiet hours, the city seems to hold its breath.",
  "Science begins with a simple question and a lot of patience. Why does the sky turn orange at sunset? Why does bread rise in a warm kitchen? A good scientist makes a guess, tests it, and accepts the answer, even when it is not the expected one. Experiments often fail many times before they work once. Each failure removes one wrong idea from the table. Slowly, step by step, a clearer picture of the world appears.",
  "People have been writing things down for more than five thousand years. The first marks were pressed into wet clay to count grain and animals. Later came papyrus, parchment and, much later, paper. For centuries every book was copied by hand, one careful letter at a time. The printing press changed everything by making books cheaper and faster to produce. Typewriters brought writing into offices, and keyboards brought it into every home. Today we type more words in a week than many people once wrote in a lifetime.",
  "The ocean covers most of our planet, yet we know surprisingly little about it. Its deepest valleys are darker and colder than any place on land. Strange fish there make their own light to find food and each other. Near the surface, whales travel thousands of miles every year. Tiny plants floating in the water produce much of the oxygen we breathe. Waves carry energy from storms that happened far across the sea. Standing on a beach, it is easy to forget how much is hidden beyond the horizon.",
  "Sleep is one of the most underrated habits for a healthy life. While we rest, the brain sorts the events of the day and stores what matters. A good night of sleep makes it easier to focus, learn and stay calm. Screens late at night can trick the body into thinking it is still day. Going to bed at the same time every night helps more than most people expect. A dark, cool and quiet room also makes a real difference. Tomorrow's best ideas often start with tonight's rest.",
  "A good friend is someone who knows your faults and stays anyway. Friendship does not need big gestures to grow strong. It grows with small messages, shared meals and long walks without a plan. Real friends tell you the truth, even when it is not what you want to hear. They celebrate your wins as if they were their own. Distance and time can test a friendship, but they rarely break a true one. Sometimes a single phone call is enough to make years disappear.",
  "Gardening teaches patience in a way few other hobbies can. You plant a seed, water it, and then you wait. For days nothing seems to happen above the soil. Then a tiny green shoot pushes through, fragile and determined. Tomatoes need sun, basil needs warmth, and mint grows almost everywhere. Weeds, snails and sudden frost will test your good humor. Picking the first ripe fruit you grew yourself feels like a small victory.",
  "Libraries are among the most generous places in any town. Anyone can walk in, sit down and read for free for hours. The shelves hold stories, maps, recipes and the history of entire nations. Librarians can help you find almost anything, even when you do not know what to ask. Many libraries now lend laptops, music and even tools. Children discover their first favorite book there, often by pure chance. A quiet corner with a good book is still one of life's simple pleasures.",
  "Mountains have a way of making every problem feel smaller. The climb starts easily on a wide path through green meadows. Soon the trail turns steep, rocky and narrow. Your legs burn and each breath feels shorter than the last. Then, after one more bend, the whole valley opens below you. Rivers look like silver threads and villages like scattered toys. At the top, nobody speaks for a while; the view says enough.",
  "Working from home has its own rewards and its own challenges. There is no long commute and no crowded train in the morning. Lunch can be cooked in your own kitchen, and the dog is always nearby. On the other hand, the line between work and rest can quickly blur. It helps to keep a separate desk and a fixed schedule. Short breaks and a walk outside keep the mind fresh. At the end of the day, closing the laptop should mean the work is done.",
  "The night sky has guided travelers for thousands of years. Sailors used the stars to find their way across open water. Farmers watched the moon to know when to plant and when to harvest. Today city lights hide most of the stars from our eyes. Far from town, on a clear night, the sky looks crowded and alive. You can see planets, satellites and the pale band of our own galaxy. Looking up for a few minutes is a quiet reminder of how vast the universe is.",
  "Good habits are built in small steps, not giant leaps. Instead of promising to run ten miles, start by walking around the block. Instead of reading a whole book in a weekend, read ten pages before bed. Small wins are easy to repeat, and repetition is what makes a habit stick. Missing one day is normal; missing two in a row is where habits break. Tracking your progress can make the effort visible and even fun. After a few months, the new routine simply feels like part of who you are.",
  "Markets are full of color, noise and delicious smells. Farmers arrive early to stack their fruit and vegetables in neat piles. Vendors call out prices while customers taste cheese, olives and fresh bread. A good market changes with the seasons, from strawberries in spring to pumpkins in autumn. Shopping there is slower than at a supermarket, but it is far more interesting. You learn where your food comes from and who grew it. Often you leave with more than you planned, and a new recipe to try.",
];
