import { createApp } from "vue";
import "./style.css";
import App from "./App.vue";
import router from "./router";
import { createPinia } from "pinia";
import { revealDirective } from "@/shared/directives/reveal";
const app = createApp(App);
app.directive("reveal", revealDirective);
app.use(router);
app.use(createPinia());
app.mount("#app");
